apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # Actívalo solo si ya tienes cert-manager instalado y quieres crear el ClusterIssuer desde este repo.
  - clusterissuer-letsencrypt.yaml

images:
  - name: hostyourself
    newName: ghcr.io/acardoco/hostyourself_web
    newTag: initial
