apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # Actívalo solo si ya tienes cert-manager instalado y quieres crear el ClusterIssuer desde este repo.
  - clusterissuer-letsencrypt.yaml

images:
  - name: hostyourself
<<<<<<< HEAD
    newName: ghcr.io/acardoco/hostyourself
    newTag: initial
=======
    newName: ghcr.io/acardoco/hostyourself_web
    newTag: latest
>>>>>>> f50a50133e8250521d7d9ad1ffcb408b10657766
